name: TeamSurvival
main: nmt.minecraft.TeamSurvival.TeamSurvivalPlugin
version: 0.1
permissions:
    teamsurvival.*:
        children:
            teamsurvival.team.create: true
            teamsurvival.team.disband: true
            teamsurvival.team.info: true
            teamsurvival.session.create: true
            teamsurvival.session.start: true
            teamsurvival.session.info: true
            teamsurvival.session.stop: true
            teamsurvival.creator.new: true
            teamsurvival.creator.open: true
            teamsurvival.creator.close: true
            teamsurvival.creator.setshop: true
            teamsurvival.creator.addarena: true
        default: op
    teamsurvival.team.join:
      default: true
commands:
    teamsurvival:
        permission: teamsurvival.*
        usage: /ts [session|team] {args}
        description: Container command for admin-level commands
        aliases: ts
    jointeam:
        permission: teamsurvival.team.join
        ussage: /jointeam [teamname]
        description: Joins a TeamSurvival team
        aliases: join
    teamsurvivalcreator:
        permission: teamsurvival.creator.*
        usage: /tsc [open|close|setShop|setStartingLocation|addArena|setShopButton|info] {args}
        description: Container commmand for arena creation commands
        aliases: tsc
    